CREATE DATABASE DBTEST;
USE DBTEST;

CREATE TABLE DEPARTMENT(
DEPTNO int,
DEPTNAME varchar(15),
FLOOR int,
CONSTRAINT PK_D PRIMARY KEY DEPARTMENT(DEPTNO)
);

CREATE TABLE EMPLOYEE(
EMPNO int,
EMPNAME varchar(15),
DNO int,
CONSTRAINT PK_E PRIMARY KEY EMPLOYEE(EMPNO),
CONSTRAINT FK_D FOREIGN KEY (DNO) REFERENCES DEPARTMENT(DEPTNO)
);

INSERT INTO DEPARTMENT
VALUE(1,'영업',8),
(2,'기획',10),
(3,'개발',9);

INSERT INTO EMPLOYEE
VALUE(2106,'김창섭',2),
(3426,'박영권',3),
(3011,'이수민',1),
(1003,'조민희',1),
(3427,'최종철',3);

SELECT *
FROM EMPLOYEE E
WHERE EXISTS
	(SELECT *
	FROM DEPARTMENT D
	WHERE E.DNO=D.DEPTNO
		AND (DEPTNAME='영업' OR DEPTNAME='개발'));
        
SELECT *
FROM EMPLOYEE
WHERE DNO IN (
	SELECT DEPTNO
    	FROM DEPARTMENT
    	WHERE DEPTNAME='영업' OR DEPTNAME='개발');
        
        